# render.yaml
services:
  - type: worker
    name: card-bank-bot
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python card_bank_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: APININJAS_KEY
        sync: false
